Repository apollographql/router, pull requests merged in 2021-12, with the labels that each got.

#234 Cleanup snapshots
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__model__tests__query_plan_from_json.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__plan.snap
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/otlp/snapshots/apollo_router__configuration__otlp__grpc__header_map_serde__tests__serialize_metadata_map.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-2.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-3.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change-4.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc-2.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_grpc.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http-2.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_http.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__ensure_configuration_api_does_not_change_tls_config.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__supergraph_config_serde.snap
  apollo-router/tests/snapshots/infrastructure_tests__starstuff_supergraph_is_valid.snap
Labels: size/small

#232 Add jaeger for development again
  DEVELOPMENT.md
  examples/config-jaeger.yml
Labels: size/small

#231 Update Rust edition to 2021
  apollo-router-benchmarks/Cargo.toml
  apollo-router-core/Cargo.toml
  apollo-router/Cargo.toml
  xtask/Cargo.toml
Labels: size/small

#225 Refactor cache parameters
  apollo-router-core/src/query_planner/caching_query_planner.rs
  apollo-router-core/src/query_planner/router_bridge_query_planner.rs
  apollo-router-core/src/traits.rs
  apollo-router/src/apollo_router.rs
  apollo-router/src/lib.rs
  apollo-router/src/main.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/state_machine.rs
  apollo-router/tests/integration_tests.rs
Labels: size/small

#233 Refactor model.rs & QueryPlanner related stuff
  apollo-router-core/src/error.rs
  apollo-router-core/src/query_planner/mod.rs
  apollo-router-core/src/query_planner/model.rs
  apollo-router-core/src/query_planner/router_bridge_query_planner.rs
  apollo-router-core/src/query_planner/selection.rs
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__plan.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__tests__query_plan_from_json.snap
  apollo-router-core/src/query_planner/testdata/query_plan.json
  apollo-router-core/src/response.rs
  apollo-router/src/apollo_router.rs
  apollo-router/tests/fixtures/query_plan.json
Labels: size/small

#136 feat: Display schema parse errors.
  Cargo.lock
  apollo-router-core/Cargo.toml
  apollo-router-core/src/error.rs
  apollo-router-core/src/query.rs
  apollo-router-core/src/schema.rs
  licenses.html
Labels: enhancement

#256 chore: adjusting pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: size/small, 2021-12

#227 Query variables validation
  Cargo.lock
  apollo-router-core/Cargo.toml
  apollo-router-core/src/error.rs
  apollo-router-core/src/query_cache.rs
  apollo-router-core/src/query_planner/mod.rs
  apollo-router-core/src/spec/field_type.rs
  apollo-router-core/src/spec/fragments.rs
  apollo-router-core/src/spec/mod.rs
  apollo-router-core/src/spec/query.rs
  apollo-router-core/src/spec/schema.rs
  apollo-router-core/src/spec/selection.rs
  apollo-router/src/apollo_router.rs
  apollo-router/src/lib.rs
  apollo-router/src/state_machine.rs
  apollo-router/tests/integration_tests.rs
  licenses.html
Labels: size/medium

#263 Improve health checks
  apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__health_check.snap
  apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_body.snap
  apollo-router/src/snapshots/apollo_router__warp_http_server_factory__tests__it_provides_health_status_header.snap
  apollo-router/src/warp_http_server_factory.rs
Labels: size/small

#269 Update router-bridge dependency to make use of recently introduced deno-core snapshot based execution
  .circleci/config.yml
  Cargo.lock
  apollo-router-core/Cargo.toml
  licenses.html
Labels: size/small, 2021-12
