Repository apollographql/router, pull requests merged in 2022-04, with the labels that each got.

#738 add support of metrics
  CHANGELOG.md
  Cargo.lock
  apollo-router-core/src/layers/ensure_query_presence.rs
  apollo-router-core/src/plugin.rs
  apollo-router-core/src/plugins/traffic_shaping.rs
  apollo-router-core/src/services/mod.rs
  apollo-router-core/src/services/router_service.rs
  apollo-router/Cargo.toml
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/http_server_factory.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/metrics.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/otlp/http.rs
  apollo-router/src/plugins/telemetry/otlp/mod.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/state_machine.rs
  apollo-router/src/warp_http_server_factory.rs
  docs/source/configuration/header-propagation.mdx
  docs/source/configuration/opentelemetry.mdx
  licenses.html
Labels: component/plugins

#751 Switch from warp to axum
  .circleci/config.yml
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-core/Cargo.toml
  apollo-router-core/src/services/http_compat.rs
  apollo-router-core/src/services/router_service.rs
  apollo-router/Cargo.toml
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/lib.rs
  licenses.html
Labels: component/http

#873 fix: Correctly flag incoming POST requests.
  NEXT_CHANGELOG.md
  apollo-router-core/src/query_planner/mod.rs
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/plugins/override_url.rs
  apollo-router/tests/integration_tests.rs
Labels: bug

#884 fix: Restore the health check route
  NEXT_CHANGELOG.md
  apollo-router/src/axum_http_server_factory.rs
Labels: bug

#891 docs: use true path of "apollo telemetry" in sidebar config
  docs/source/config.json
Labels: documentation
