Repository apollographql/router, pull requests merged in 2022-09, with the labels that each got.

#1689 release: v1.0.0-alpha.1
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  docs/source/federation-version-support.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  uplink/Cargo.toml
  xtask/Cargo.toml
Labels: release

#1707 release: v1.0.0-alpha.2
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  uplink/Cargo.toml
  xtask/Cargo.toml
Labels: release

#1705 fix(metrics): compute time before receiving the first response from the stream each time
  NEXT_CHANGELOG.md
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/mod.rs
Labels: bug

#1717 release: v1.0.0-alpha.3
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  uplink/Cargo.toml
  xtask/Cargo.toml
Labels: release

#1724 docs: updates federation version support table for alpha.3
  docs/source/federation-version-support.mdx
Labels: documentation

#1746 remove some over-exposed functions from the public API
  NEXT_CHANGELOG.md
  apollo-router/src/services/subgraph.rs
  apollo-router/src/services/supergraph.rs
  licenses.html
Labels: 1.0

#1630 add notice about anonymous telemetry data collection
  apollo-router/src/executable.rs
  docs/source/config.json
  docs/source/privacy.mdx
Labels: 1.0

#1775 release: v1.0.0-rc.0
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  docs/source/federation-version-support.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  xtask/Cargo.toml
Labels: release

#1640 Get variable default values from the query for query plan condition nodes
  NEXT_CHANGELOG.md
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/query_planner/caching_query_planner.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/services/query_planner.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/spec/query.rs
  apollo-router/src/spec/query/tests.rs
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/snapshots/integration_tests__defer_default_variable-2.snap
  apollo-router/tests/snapshots/integration_tests__defer_default_variable-3.snap
  apollo-router/tests/snapshots/integration_tests__defer_default_variable.snap
Labels: component/defer

#1810 release: v1.0.0-rc.1
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  docs/source/federation-version-support.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  xtask/Cargo.toml
Labels: release

#1845 release: v1.0.0-rc.2
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
  xtask/Cargo.toml
Labels: release

#1867 release: v1.0.0
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
  xtask/Cargo.toml
Labels: release

#1738 docs: `@defer` support
  docs/source/_redirects
  docs/source/config.json
  docs/source/executing-operations/build-run-queries.mdx
  docs/source/executing-operations/defer-support.mdx
  docs/source/executing-operations/requests.mdx
Labels: documentation

#1846 split axum_http_server_factory in multiple files
  apollo-router/src/axum_factory/axum_http_server_factory.rs
  apollo-router/src/axum_factory/handlers.rs
  apollo-router/src/axum_factory/listeners.rs
  apollo-router/src/axum_factory/mod.rs
  apollo-router/src/axum_factory/tests.rs
  apollo-router/src/axum_factory/utils.rs
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/lib.rs
  apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
  apollo-router/src/router.rs
  apollo-router/src/test_harness.rs
Labels: refactoring
