Repository apollographql/router, pull requests merged in 2022-05, with the labels that each got.

#963 fix: improve the configuration error report
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_bad_type.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_errors_after_first_field.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_inline_sequence.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__line_precise_config_errors_with_sequence.snap
  apollo-router/src/configuration/snapshots/apollo_router__configuration__yaml__test__test.snap
  apollo-router/src/configuration/yaml.rs
Labels: bug

#898 feat: Usage Reporting.
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-core/Cargo.toml
  apollo-router-core/src/error.rs
  apollo-router-core/src/layers/map_future_with_context.rs
  apollo-router-core/src/layers/mod.rs
  apollo-router-core/src/lib.rs
  apollo-router-core/src/plugin/utils/test/mock/canned.rs
  apollo-router-core/src/plugin/utils/test/mock/mod.rs
  apollo-router-core/src/plugin/utils/test/mod.rs
  apollo-router-core/src/plugins/forbid_mutations.rs
  apollo-router-core/src/query_planner/bridge_query_planner.rs
  apollo-router-core/src/query_planner/caching_query_planner.rs
  apollo-router-core/src/query_planner/mod.rs
  apollo-router-core/src/query_planner/selection.rs
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__empty_query_plan_should_be_a_planner_error.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__empty_query_plan_usage_reporting.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan_invalid_query_errors.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan_invalid_query_usage_reporting.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan_root.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan_usage_reporting.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__model__tests__query_plan_from_json.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__empty_query_plan_should_be_a_planner_error.snap
  apollo-router-core/src/query_planner/snapshots/apollo_router_core__query_planner__router_bridge_query_planner__tests__plan.snap
  apollo-router-core/src/services/execution_service.rs
  apollo-router-core/src/services/layers/allow_only_http_post_mutations.rs
  apollo-router-core/src/services/mod.rs
  apollo-router-core/src/services/router_service.rs
  apollo-router-core/src/spec/query.rs
  apollo-router-core/src/spec/schema.rs
  apollo-router/Cargo.toml
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/telemetry/apollo.rs
  apollo-router/src/plugins/telemetry/metrics/apollo.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__aggregation.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_exclude.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_multiple_operations.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_parse_failure.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_single_operation.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_unknown_operation.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_validation_failure.snap
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/tracing/apollo.rs
  apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/state_machine.rs
  apollo-router/src/testdata/minimal_supergraph.graphql
  apollo-router/tests/integration_tests.rs
  apollo-spaceport/Cargo.toml
  apollo-spaceport/build.rs
  apollo-spaceport/proto/agents.proto
  apollo-spaceport/src/lib.rs
  apollo-spaceport/src/server.rs
  apollo-spaceport/src/spaceport.rs
  licenses.html
Labels: feature

#1000 add documentation for the endpoint configuration in server
  NEXT_CHANGELOG.md
  docs/source/configuration/overview.mdx
Labels: documentation

#1092 fix(configuration): let the user use the environment variable expansion
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/configuration/testdata/tracing_apollo_env.router.yaml
  apollo-router/src/configuration/testdata/tracing_datadog_env.router.yaml
  apollo-router/src/configuration/testdata/tracing_jaeger_collector_env.router.yaml
  apollo-router/src/configuration/testdata/tracing_otlp_grpc_basic_env.router.yaml
  apollo-router/src/configuration/testdata/zipkin-url_env.router.yaml
  apollo-router/src/plugins/telemetry/apollo.rs
  apollo-router/src/plugins/telemetry/otlp.rs
  apollo-router/src/plugins/telemetry/tracing/datadog.rs
  apollo-router/src/plugins/telemetry/tracing/jaeger.rs
Labels: bug

#1098 fix: fix the installation script for windows with the extension
  NEXT_CHANGELOG.md
  scripts/install.sh
  xtask/src/commands/package/mod.rs
Labels: bug

#1100 fix the introspection query detection
  NEXT_CHANGELOG.md
  apollo-router-core/src/spec/query.rs
Labels: bug
