Repository apollographql/router, pull requests merged in 2022-11, with the labels that each got.

#1940 docs: add a note about --dev mode config equivalent
  docs/source/quickstart.mdx
Labels: documentation

#2103 deps: Update `apollo-parser` to `v0.3.2`
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  examples/supergraph-sdl/rust/Cargo.toml
  fuzz/Cargo.toml
Labels: dependencies

#2006 Request retries for subgraph queries
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/plugins/traffic_shaping/retry.rs
  apollo-router/src/services/subgraph.rs
  docs/source/configuration/traffic-shaping.mdx
Labels: experimental

#2131 add configuration for trace_id
  NEXT_CHANGELOG.md
  apollo-router/src/axum_factory/utils.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/telemetry/apollo.rs
  apollo-router/src/plugins/telemetry/config.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/tracing/apollo.rs
  apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
  apollo-router/src/router.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/testdata/jaeger.router.yaml
  apollo-router/tests/common.rs
  apollo-router/tests/jaeger_test.rs
  apollo-router/tests/zipkin_test.rs
  docs/source/configuration/tracing.mdx
Labels: experimental
