Repository apollographql/router, pull requests merged in 2022-03, with the labels that each got.

#597 release: v0.1.0-alpha.8
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-core/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  deny.toml
  xtask/Cargo.toml
Labels: release

#631 docs: Use "Customizations" instead of "Plugins" header
  docs/gatsby-config.js
  docs/source/config.json
  docs/source/customizations/native.mdx
  docs/source/customizations/overview.mdx
  docs/source/customizations/rhai.mdx
Labels: documentation

#627 docs: header propagation content moves from overview into dedicated page
  docs/source/configuration/header-propagation.mdx
  docs/source/configuration/overview.mdx
Labels: documentation

#659 Doc updates for telemetry
  docs/source/config.json
  docs/source/configuration/open-telemetry.mdx
  docs/source/configuration/spaceport.mdx
  docs/source/configuration/telemetry.mdx
  docs/source/spaceport.mdx
Labels: documentation

#667 docs: subgraph URL override
  apollo-router/src/plugins/override_url.rs
  docs/source/configuration/subgraph-routing-urls.mdx
Labels: documentation

#673 document native customizations
  Cargo.toml
  docs/source/customizations/native.mdx
  docs/source/customizations/overview.mdx
  examples/async-auth/Cargo.toml
  examples/async-auth/README.md
  examples/async-auth/allowedClientIds.json
  examples/async-auth/router.yaml
  examples/async-auth/src/allow_client_id_from_file.rs
  examples/async-auth/src/main.rs
  examples/context/Cargo.toml
  examples/context/README.md
  examples/context/router.yaml
  examples/context/src/context_data.rs
  examples/context/src/main.rs
  examples/embedded/Cargo.toml
  examples/embedded/README.md
  examples/embedded/router.yaml
  examples/embedded/src/main.rs
  examples/forbid-anonymous-operations/README.md
  examples/forbid-anonymous-operations/router.yaml
  examples/forbid-anonymous-operations/src/main.rs
  examples/graphql/README.md
  examples/header-manpiulation/README.md
  examples/header-manpiulation/router.yaml
  examples/hello-world/README.md
  examples/hello-world/router.yaml
  examples/hello-world/src/hello_world.rs
  examples/hello-world/src/main.rs
  examples/jwt-auth/README.md
  examples/jwt-auth/router.yaml
  examples/jwt-auth/src/main.rs
  examples/status-code-propagation/Cargo.toml
  examples/status-code-propagation/README.md
  examples/status-code-propagation/router.yaml
  examples/status-code-propagation/src/main.rs
  examples/status-code-propagation/src/propagate_status_code.rs
  examples/telemetry/README.md
  examples/telemetry/otlp.router.yaml
  examples/unix-sockets/README.md
  examples/unix-sockets/router.yaml
Labels: documentation

#687 docs: initial migrating from gateway
  docs/source/migrating-from-gateway.mdx
Labels: documentation

#695 docs: follow-up to gateway migration in #687
  docs/source/migrating-from-gateway.mdx
Labels: documentation

#696 docs: Reference "DEVELOPMENT.md" in docs for building from source
  docs/source/build-from-source.mdx
  docs/source/config.json
  docs/source/quickstart.mdx
Labels: documentation

#701 docs: pre-preview editorial
  docs/source/config.json
  docs/source/configuration/cors.mdx
  docs/source/configuration/header-propagation.mdx
  docs/source/configuration/logging.mdx
  docs/source/configuration/opentelemetry.mdx
  docs/source/configuration/overview.mdx
  docs/source/configuration/spaceport.mdx
  docs/source/configuration/subgraph-routing-urls.mdx
  docs/source/customizations/native.mdx
  docs/source/customizations/overview.mdx
  docs/source/customizations/rhai.mdx
  docs/source/development-workflow/build-run-queries.mdx
  docs/source/development-workflow/requests.mdx
  docs/source/migrating-from-gateway.mdx
  docs/source/quickstart.mdx
Labels: documentation

#705 fix: take the current path of the http request and put it into the router request #699
  CHANGELOG.md
  apollo-router/src/warp_http_server_factory.rs
Labels: bug

#707 docs: fix a typo in configuration overview
  docs/source/configuration/overview.mdx
Labels: documentation

#704 release: v0.1.0-alpha.10
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-core/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  deny.toml
  xtask/Cargo.toml
Labels: release

#718 release: v0.1.0-preview.0
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-core/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  deny.toml
  xtask/Cargo.toml
Labels: release
