Repository apollographql/router, pull requests merged in 2022-06, with the labels that each got.

#1159 add more customizable metrics
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/telemetry/config.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/metrics/prometheus.rs
  apollo-router/src/plugins/telemetry/mod.rs
  docs/source/configuration/metrics.mdx
Labels: enhancement, component/plugins

#872 Variable deduplication in query planner
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/json_ext.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/query_planner/caching_query_planner.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/snapshots/apollo_router_core__query_planner__bridge_query_planner__tests__plan.snap
  apollo-router/src/services/mod.rs
  apollo-router/src/services/router_service.rs
  docs/source/configuration/traffic-shaping.mdx
Labels: performance

#1216 Remove apollo_router::prelude::graphql reexports
  NEXT_CHANGELOG.md
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/context.rs
  apollo-router/src/error.rs
  apollo-router/src/http_server_factory.rs
  apollo-router/src/introspection.rs
  apollo-router/src/json_ext.rs
  apollo-router/src/lib.rs
  apollo-router/src/query_cache.rs
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/query_planner/caching_query_planner.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/selection.rs
  apollo-router/src/request.rs
  apollo-router/src/response.rs
  apollo-router/src/router.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/services/router_service.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/spec/query.rs
  apollo-router/src/state_machine.rs
  apollo-router/src/traits.rs
  apollo-router/tests/infrastructure_tests.rs
  apollo-router/tests/integration_tests.rs
Labels: api/1.0

#1226 checkpoint_async() shouldn't require a boxed argument
  apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs
  apollo-router/src/layers/async_checkpoint.rs
  apollo-router/src/layers/mod.rs
  examples/async-auth/src/allow_client_id_from_file.rs
Labels: api/1.0

#1229 Add compression support
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/error.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
  apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
  docs/source/configuration/traffic-shaping.mdx
  licenses.html
Labels: feature

#1267 Flatten the public API of apollo_router::plugin
  apollo-router-benchmarks/src/shared.rs
  apollo-router/src/layers/async_checkpoint.rs
  apollo-router/src/layers/cache.rs
  apollo-router/src/layers/map_future_with_context.rs
  apollo-router/src/layers/sync_checkpoint.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugin/serde.rs
  apollo-router/src/plugin/test/mock/canned.rs
  apollo-router/src/plugin/test/mock/mod.rs
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugin/test/mod.rs
  apollo-router/src/plugin/test/service.rs
  apollo-router/src/plugin/test/snapshots/apollo_router__plugin__test__testing__test_harness.snap
  apollo-router/src/plugin/utils/mod.rs
  apollo-router/src/plugin/utils/test/mock/mod.rs
  apollo-router/src/plugin/utils/test/snapshots/apollo_router__plugin__utils__test__test__test_harness.snap
  apollo-router/src/plugins/csrf.rs
  apollo-router/src/plugins/forbid_mutations.rs
  apollo-router/src/plugins/headers.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/override_url.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/apollo.rs
  apollo-router/src/plugins/telemetry/metrics/apollo.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/services/layers/allow_only_http_post_mutations.rs
  apollo-router/src/services/layers/apq.rs
  apollo-router/src/services/layers/ensure_query_presence.rs
  examples/add-timestamp-header/src/main.rs
  examples/async-auth/src/allow_client_id_from_file.rs
  examples/cookies-to-headers/src/main.rs
  examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
  examples/hello-world/src/hello_world.rs
  examples/jwt-auth/src/jwt.rs
  examples/op-name-to-header/src/main.rs
  examples/rhai-data-response-mutate/src/main.rs
  examples/rhai-error-response-mutate/src/main.rs
  examples/rhai-logging/src/main.rs
  examples/rhai-surrogate-cache-key/src/main.rs
  examples/status-code-propagation/src/propagate_status_code.rs
Labels: api/1.0

#1285 Add changelog for public API rework
  NEXT_CHANGELOG.md
Labels: api/1.0

#1303 Move apollo_router::{Request, Response, error::Error} to a new graphql module
  NEXT_CHANGELOG.md
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/error.rs
  apollo-router/src/graphql.rs
  apollo-router/src/http_server_factory.rs
  apollo-router/src/introspection.rs
  apollo-router/src/lib.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugin/test/service.rs
  apollo-router/src/plugins/forbid_mutations.rs
  apollo-router/src/plugins/headers.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/traffic_shaping/deduplication.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/selection.rs
  apollo-router/src/router.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/services/execution_service.rs
  apollo-router/src/services/layers/allow_only_http_post_mutations.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/services/router_service.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/spec/query.rs
  apollo-router/src/state_machine.rs
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/rhai_tests.rs
  examples/async-auth/src/allow_client_id_from_file.rs
  examples/cookies-to-headers/src/main.rs
  examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
  examples/hello-world/src/hello_world.rs
  examples/jwt-auth/src/jwt.rs
Labels: api/1.0
