Repository apollographql/router, pull requests merged in 2022-08, with the labels that each got.

#1347 add support of rate limit and timeout
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/plugins/traffic_shaping/rate/error.rs
  apollo-router/src/plugins/traffic_shaping/rate/future.rs
  apollo-router/src/plugins/traffic_shaping/rate/layer.rs
  apollo-router/src/plugins/traffic_shaping/rate/mod.rs
  apollo-router/src/plugins/traffic_shaping/rate/rate.rs
  apollo-router/src/plugins/traffic_shaping/rate/service.rs
  apollo-router/src/plugins/traffic_shaping/timeout/error.rs
  apollo-router/src/plugins/traffic_shaping/timeout/future.rs
  apollo-router/src/plugins/traffic_shaping/timeout/layer.rs
  apollo-router/src/plugins/traffic_shaping/timeout/mod.rs
  docs/source/configuration/traffic-shaping.mdx
Labels: component/plugins, feature, api/1.0

#1486 refactor(query_planner): put queryplan options in private and wrap QueryPlanContent in an opaque type
  NEXT_CHANGELOG.md
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/services/router_service.rs
Labels: api/1.0

#1502 fix(deps): update cargo pre-1.0 packages but not for `tracing*`
  Cargo.lock
  apollo-router/Cargo.toml
  fuzz/Cargo.toml
  licenses.html
Labels: dependencies

#1506 docs: rename "client awareness" and add to sidebar
  docs/source/_redirects
  docs/source/config.json
  docs/source/managed-federation/client-awareness.mdx
Labels: documentation

#1509 deps: group and justify holding back `tracing` and `opentelemetry` version bumps
  apollo-router/Cargo.toml
  renovate.json5
Labels: component/infra

#1525 Add {Router,Execution}Response::map_stream helper
  apollo-router/src/services/http_ext.rs
  apollo-router/src/services/mod.rs
  examples/cookies-to-headers/src/main.rs
Labels: api/1.0

#1534 Rename pipeline stages
  NEXT_CHANGELOG.md
  apollo-router-benchmarks/src/shared.rs
  apollo-router-scaffold/templates/plugin/src/plugins/{{snake_name}}.rs
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/layers/map_future_with_context.rs
  apollo-router/src/layers/mod.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugin/test/mod.rs
  apollo-router/src/plugin/test/service.rs
  apollo-router/src/plugins/csrf.rs
  apollo-router/src/plugins/expose_query_plan.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/metrics/apollo.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/services/layers/apq.rs
  apollo-router/src/services/layers/ensure_query_presence.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/stages.rs
  apollo-router/src/test_harness.rs
  apollo-router/tests/fixtures/test.rhai
  apollo-router/tests/fixtures/test_callbacks.rhai
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/rhai_tests.rs
  apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
  apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
  docs/source/customizations/native.mdx
  docs/source/customizations/overview.mdx
  docs/source/customizations/rhai.mdx
  examples/add-timestamp-header/src/add_timestamp_header.rhai
  examples/add-timestamp-header/src/main.rs
  examples/async-auth/README.md
  examples/async-auth/src/allow_client_id_from_file.rs
  examples/context/src/context_data.rs
  examples/cookies-to-headers/src/main.rs
  examples/embedded/src/main.rs
  examples/forbid-anonymous-operations/README.md
  examples/forbid-anonymous-operations/src/forbid_anonymous_operations.rs
  examples/hello-world/src/hello_world.rs
  examples/jwt-auth/README.md
  examples/jwt-auth/src/jwt.rs
  examples/op-name-to-header/src/main.rs
  examples/op-name-to-header/src/op_name_to_header.rhai
  examples/rhai-data-response-mutate/src/main.rs
  examples/rhai-data-response-mutate/src/rhai_data_response_mutate.rhai
  examples/rhai-error-response-mutate/src/main.rs
  examples/rhai-error-response-mutate/src/rhai_error_response_mutate.rhai
  examples/rhai-logging/src/main.rs
  examples/rhai-logging/src/rhai_logging.rhai
  examples/rhai-subgraph-request-log/src/main.rs
  examples/rhai-surrogate-cache-key/src/main.rs
  examples/rhai-surrogate-cache-key/src/rhai_surrogate_cache_key.rhai
  examples/status-code-propagation/src/propagate_status_code.rs
  examples/supergraph_sdl/src/supergraph_sdl.rs
Labels: api/1.0

#1526 Warn on missing docs, with allow exceptions to be removed progressively
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/mod.rs
  apollo-router/src/error.rs
  apollo-router/src/graphql.rs
  apollo-router/src/layers/cache.rs
  apollo-router/src/layers/instrument.rs
  apollo-router/src/layers/map_future_with_request_data.rs
  apollo-router/src/layers/sync_checkpoint.rs
  apollo-router/src/lib.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugin/serde.rs
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugin/test/service.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/request.rs
  apollo-router/src/response.rs
  apollo-router/src/router.rs
  apollo-router/src/services/http_ext.rs
  apollo-router/src/services/mod.rs
  apollo-router/src/stages.rs
  apollo-router/src/test_harness.rs
Labels: api/1.0

#1555 Rename RouterService to SupergraphService in various places
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/http_server_factory.rs
  apollo-router/src/plugins/expose_query_plan.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/router.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/state_machine.rs
  apollo-router/src/test_harness.rs
  docs/source/customizations/native.mdx
  docs/source/customizations/overview.mdx
  examples/context/README.md
  examples/status-code-propagation/README.md
  examples/status-code-propagation/src/propagate_status_code.rs
  examples/supergraph_sdl/README.md
Labels: api/1.0

#1557 activate defer support in introspection
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  apollo-router/src/introspection.rs
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/services/supergraph_service.rs
Labels: component/defer

#1551 support the incremental response field
  NEXT_CHANGELOG.md
  apollo-router/src/error.rs
  apollo-router/src/response.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/snapshots/integration_tests__defer_path-2.snap
  apollo-router/tests/snapshots/integration_tests__defer_path.snap
  apollo-router/tests/snapshots/integration_tests__defer_path_in_array-2.snap
  apollo-router/tests/snapshots/integration_tests__defer_path_in_array.snap
Labels: component/defer

#1563 Change a telemetry span name from "router" to "supergraph"
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/tests/jaeger_test.rs
  apollo-router/tests/snapshots/integration_tests__traced_basic_composition.snap
  apollo-router/tests/snapshots/integration_tests__traced_basic_request.snap
Labels: api/1.0

#1568 Make QueryPlan::usage_reporting and QueryPlannerContent private
  NEXT_CHANGELOG.md
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/services/execution.rs
  apollo-router/src/services/query_planner.rs
  apollo-router/src/spec/query.rs
Labels: api/1.0

#1589 Make http_ext::Request and http_ext::Response private
  NEXT_CHANGELOG.md
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/context.rs
  apollo-router/src/http_ext.rs
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugins/expose_query_plan.rs
  apollo-router/src/plugins/headers.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/traffic_shaping/deduplication.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/services/execution.rs
  apollo-router/src/services/execution_service.rs
  apollo-router/src/services/layers/allow_only_http_post_mutations.rs
  apollo-router/src/services/subgraph.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/services/supergraph.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/state_machine.rs
Labels: api/1.0

#1579 TestHarness: rename extra_*_plugin to *_hook
  NEXT_CHANGELOG.md
  apollo-router/src/test_harness.rs
  examples/add-timestamp-header/src/main.rs
  examples/cookies-to-headers/src/main.rs
  examples/op-name-to-header/src/main.rs
  examples/rhai-logging/src/main.rs
Labels: api/1.0

#1622 Make the query_planner module private
  apollo-router/src/lib.rs
  apollo-router/src/query_planner/mod.rs
Labels: 1.0

#1433 Future-proof installer script and re-introduce target triplets
  NEXT_CHANGELOG.md
  RELEASE_CHECKLIST.md
  dockerfiles/Dockerfile.router
  scripts/install.sh
  xtask/src/commands/package/mod.rs
Labels: 1.0

#1609 Rename `Server::endpoint` to `Server::graphql_path`
  NEXT_CHANGELOG.md
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  docs/source/configuration/overview.mdx
Labels: 1.0

#1610 queries with defer must have the Accept: multipart/mixed header
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  apollo-router/src/axum_http_server_factory.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/tests/integration_tests.rs
  apollo-router/tests/snapshots/integration_tests__defer_query_without_accept.snap
Labels: 1.0, component/defer

#1638 release: v1.0.0-alpha.0
  CHANGELOG.md
  Cargo.lock
  NEXT_CHANGELOG.md
  RELEASE_CHECKLIST.md
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-spaceport/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  docs/source/federation-version-support.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
  uplink/Cargo.toml
  xtask/Cargo.toml
Labels: release
