Repository apollographql/router, pull requests merged in 2023-09, with the labels that each got.

#3748 fix: handle correctly multipart stream if the original stream is empty
  .changesets/fix_bnjjj_fix_empty_multipart_stream.md
  apollo-router/src/protocols/multipart.rs
Labels: component/defer, component/subscriptions

#3773 fix(subscription): force the deduplication to be enabled by default as it's documented
  .changesets/fix_bnjjj_subscription_default_configuration.md
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/subscription.rs
Labels: component/subscriptions

#3752 test(subscription): add integration test for subscription
  .changesets/maint_bnjjj_fix_3740.md
  apollo-router/tests/common.rs
  apollo-router/tests/fixtures/subscription.router.yaml
  apollo-router/tests/subscription_load_test.rs
Labels: component/subscriptions

#3882 release: v1.30.1
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/router_factory.rs
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release
