Repository apollographql/router, pull requests merged in 2023-04, with the labels that each got.

#2898 release: v1.13.2
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-router/build/studio.rs
  apollo-router/src/plugins/telemetry/metrics/apollo/snapshots/apollo_router__plugins__telemetry__metrics__apollo__studio__test__aggregation.snap
  apollo-router/src/plugins/telemetry/metrics/apollo/studio.rs
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_multiple_operations.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_parse_failure.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_single_operation.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_unknown_operation.snap
  apollo-router/src/plugins/telemetry/metrics/snapshots/apollo_router__plugins__telemetry__metrics__apollo__test__apollo_metrics_validation_failure.snap
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/proto/reports.proto
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/spec/introspection_types.graphql
  apollo-router/src/spec/schema.rs
  apollo-router/tests/snapshots/apollo_reports__client_name.snap
  apollo-router/tests/snapshots/apollo_reports__client_version.snap
  apollo-router/tests/snapshots/apollo_reports__condition_else.snap
  apollo-router/tests/snapshots/apollo_reports__condition_if.snap
  apollo-router/tests/snapshots/apollo_reports__non_defer.snap
  apollo-router/tests/snapshots/apollo_reports__send_header.snap
  apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
  apollo-router/tests/snapshots/apollo_reports__stats.snap
  apollo-router/tests/snapshots/apollo_reports__stats_mocked.snap
  apollo-router/tests/snapshots/apollo_reports__trace_id.snap
  dockerfiles/tracing/datadog-subgraph/package-lock.json
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  dockerfiles/tracing/jaeger-subgraph/package-lock.json
  dockerfiles/tracing/zipkin-subgraph/package-lock.json
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  docs/source/federation-version-support.mdx
  examples/supergraph-sdl/rust/Cargo.toml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#2903 Helm extra labels
  .changesets/config_helm_extra_labels.md
  helm/chart/router/templates/deployment.yaml
  helm/chart/router/values.yaml
Labels: component/helm

#2947 fix: return valid GraphQL responses for invalid requests
  .changesets/fix_avery_fix_invalid_graphql_response.md
  apollo-router/src/axum_factory/tests.rs
  apollo-router/src/services/layers/content_negociation.rs
  apollo-router/src/services/router_service.rs
  apollo-router/tests/integration_tests.rs
Labels: fix

#2971 release: v1.15.1
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/Dockerfile.router
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/containerization/docker.mdx
  docs/source/containerization/kubernetes.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  helm/chart/router/templates/_helpers.tpl
  helm/chart/router/templates/deployment.yaml
  scripts/install.sh
Labels: release
