Repository apollographql/router, pull requests merged in 2023-01, with the labels that each got.

#2324 infra: Trigger webhooks when pull requests are created
  .github/workflows/github_projects_tagger.yml
Labels: component/infra

#2369 Expand many glob imports
  apollo-router/src/axum_factory/tests.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/tests.rs
  apollo-router/src/context.rs
  apollo-router/src/layers/async_checkpoint.rs
  apollo-router/src/layers/map_future_with_request_data.rs
  apollo-router/src/layers/sync_checkpoint.rs
  apollo-router/src/lib.rs
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugin/test/mod.rs
  apollo-router/src/plugin/test/service.rs
  apollo-router/src/plugins/csrf.rs
  apollo-router/src/plugins/expose_query_plan.rs
  apollo-router/src/plugins/external.rs
  apollo-router/src/plugins/forbid_mutations.rs
  apollo-router/src/plugins/headers.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/override_url.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/metrics/apollo.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/traffic_shaping/deduplication.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/query_planner/caching_query_planner.rs
  apollo-router/src/query_planner/execution.rs
  apollo-router/src/query_planner/fetch.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/plan.rs
  apollo-router/src/query_planner/selection.rs
  apollo-router/src/query_planner/tests.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/services/execution_service.rs
  apollo-router/src/services/layers/allow_only_http_post_mutations.rs
  apollo-router/src/services/layers/apq.rs
  apollo-router/src/services/router.rs
  apollo-router/src/services/router_service.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/src/spec/field_type.rs
  apollo-router/src/spec/fragments.rs
  apollo-router/src/spec/query.rs
  apollo-router/src/spec/schema.rs
  apollo-router/src/spec/selection.rs
  apollo-router/src/state_machine.rs
  apollo-router/src/test_harness.rs
Labels: chore

#2336 activate TLS for single instance redis connections
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router/Cargo.toml
  apollo-router/src/cache/redis.rs
Labels: component/cache

#2396 Fix default value parsing of integer fields of input types
  apollo-router/src/spec/query.rs
  apollo-router/src/spec/query/tests.rs
  apollo-router/src/spec/schema.rs
Labels: bug

#2417 docs: add documentation to create custom metrics in plugins
  NEXT_CHANGELOG.md
  docs/source/configuration/metrics.mdx
  docs/source/customizations/native.mdx
Labels: documentation

#2437 Add process-level memory consumption benchmark
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-benchmarks/benches/memory_use.rs
  apollo-router-benchmarks/build.rs
Labels: performance

#2435 docs(telemetry.apollo): add documentation about `send_headers` and `send_variable_value`
  NEXT_CHANGELOG.md
  docs/source/configuration/apollo-telemetry.mdx
Labels: documentation

#2452 improve `#[serde(default)]` attribute on structs
  NEXT_CHANGELOG.md
  apollo-router/src/configuration/cors.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/plugins/authentication.rs
  apollo-router/src/plugins/csrf.rs
  apollo-router/src/plugins/external.rs
  apollo-router/src/plugins/headers.rs
  apollo-router/src/plugins/include_subgraph_errors.rs
  apollo-router/src/plugins/telemetry/apollo.rs
  apollo-router/src/plugins/telemetry/config.rs
  apollo-router/src/plugins/telemetry/metrics/mod.rs
  apollo-router/src/plugins/telemetry/otlp.rs
  apollo-router/src/plugins/telemetry/tracing/mod.rs
  apollo-router/src/plugins/traffic_shaping/mod.rs
  apollo-router/src/services/layers/static_page.rs
  dev-docs/yaml-design-guidance.md
Labels: refactoring

#2479 Fix mermaid graph
  docs/source/customizations/overview.mdx
Labels: documentation

#2480 Fix the documentation to disable the Apollo telemetry
  NEXT_CHANGELOG.md
  docs/source/privacy.mdx
Labels: documentation

#2496 cargo +1.67.0 clippy --fix --all
  apollo-router-scaffold/src/lib.rs
  apollo-router-scaffold/src/plugin.rs
  apollo-router/src/axum_factory/tests.rs
  apollo-router/src/axum_factory/utils.rs
  apollo-router/src/cache/redis.rs
  apollo-router/src/configuration/expansion.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/schema.rs
  apollo-router/src/configuration/tests.rs
  apollo-router/src/configuration/upgrade.rs
  apollo-router/src/configuration/yaml.rs
  apollo-router/src/error.rs
  apollo-router/src/executable.rs
  apollo-router/src/files.rs
  apollo-router/src/introspection.rs
  apollo-router/src/json_ext.rs
  apollo-router/src/main.rs
  apollo-router/src/orbiter/mod.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugin/serde.rs
  apollo-router/src/plugins/authentication.rs
  apollo-router/src/plugins/rhai.rs
  apollo-router/src/plugins/telemetry/apollo_exporter.rs
  apollo-router/src/plugins/telemetry/formatters/text.rs
  apollo-router/src/plugins/telemetry/metrics/layer.rs
  apollo-router/src/plugins/telemetry/metrics/span_metrics_exporter.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/tracing/jaeger.rs
  apollo-router/src/plugins/telemetry/tracing/mod.rs
  apollo-router/src/plugins/telemetry/tracing/zipkin.rs
  apollo-router/src/query_planner/bridge_query_planner.rs
  apollo-router/src/query_planner/fetch.rs
  apollo-router/src/query_planner/plan.rs
  apollo-router/src/request.rs
  apollo-router/src/router.rs
  apollo-router/src/services/router.rs
  apollo-router/src/services/router_service.rs
  apollo-router/src/spec/query.rs
  apollo-router/src/spec/schema.rs
  apollo-router/src/uplink/mod.rs
  apollo-router/tests/apollo_reports.rs
  apollo-router/tests/common.rs
  apollo-router/tests/docs.rs
  apollo-router/tests/jaeger_test.rs
  examples/forbid-anonymous-operations/rhai/src/main.rs
  examples/jwt-auth/rust/src/jwt.rs
  examples/surrogate-cache-key/rhai/src/main.rs
Labels: chore

#2464 federation v2.3.0
  Cargo.lock
  NEXT_CHANGELOG.md
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router/Cargo.toml
  apollo-router/src/json_ext.rs
  apollo-router/src/query_planner/fetch.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/rewrites.rs
  apollo-router/src/query_planner/snapshots/apollo_router__query_planner__bridge_query_planner__tests__plan_root.snap
  apollo-router/src/query_planner/snapshots/apollo_router__query_planner__tests__query_plan_from_json.snap
  apollo-router/src/query_planner/tests.rs
  apollo-router/src/services/supergraph_service.rs
  apollo-router/tests/fixtures/expected_response_with_queryplan.json
Labels: at
