Repository apollographql/router, pull requests merged in 2023-10, with the labels that each got.

#4037 fix(subscription): if response only contains extensions, forward them
  apollo-router/src/protocols/multipart.rs
Labels: component/subscriptions

#3885 Rhai: support alternative base64 alphabets
  .changesets/feat_geal_base64_alphabets.md
  apollo-router/src/plugins/rhai/engine.rs
  apollo-router/src/plugins/rhai/tests.rs
  docs/source/customizations/rhai-api.mdx
Labels: component/rhai

#4057 Propagate headers for source stream events with subscription
  .changesets/fix_bnjjj_fix_3731.md
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/services/supergraph_service.rs
Labels: component/subscriptions

#4066 release: v1.33.1
  CHANGELOG.md
  Cargo.lock
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.toml
  apollo-router/Cargo.toml
  apollo-router/src/axum_factory/axum_http_server_factory.rs
  apollo-router/src/axum_factory/utils.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/proto/reports.proto
  apollo-router/src/services/layers/query_analysis.rs
  apollo-router/tests/common.rs
  apollo-router/tests/metrics_tests.rs
  apollo-router/tests/snapshots/apollo_reports__batch_send_header.snap
  apollo-router/tests/snapshots/apollo_reports__batch_trace_id.snap
  apollo-router/tests/snapshots/apollo_reports__client_name.snap
  apollo-router/tests/snapshots/apollo_reports__client_version.snap
  apollo-router/tests/snapshots/apollo_reports__condition_else.snap
  apollo-router/tests/snapshots/apollo_reports__condition_if.snap
  apollo-router/tests/snapshots/apollo_reports__non_defer.snap
  apollo-router/tests/snapshots/apollo_reports__send_header.snap
  apollo-router/tests/snapshots/apollo_reports__send_variable_value.snap
  apollo-router/tests/snapshots/apollo_reports__stats.snap
  apollo-router/tests/snapshots/apollo_reports__trace_id.snap
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release
