Repository apollographql/router, pull requests merged in 2025-06, with the labels that each got.

#7587 feat(federation): ported `checkFeatureSupport` function and its tests
  apollo-federation/cli/src/main.rs
  apollo-federation/examples/api_schema.rs
  apollo-federation/src/error/mod.rs
  apollo-federation/src/lib.rs
  apollo-federation/src/link/spec.rs
  apollo-federation/src/link/spec_definition.rs
  apollo-federation/src/sources/connect/expand/mod.rs
  apollo-federation/tests/core_test.rs
  apollo-federation/tests/main.rs
  apollo-federation/tests/query_plan/build_query_plan_support.rs
  apollo-router/src/spec/schema.rs
  apollo-router/src/uplink/testdata/schema_enforcement_spec_version_out_of_range.graphql
Labels: component/query-planning

#7584 port enum_type code from JS
  apollo-federation/src/error/mod.rs
  apollo-federation/src/link/inaccessible_spec_definition.rs
  apollo-federation/src/link/join_spec_definition.rs
  apollo-federation/src/merger/merger.rs
Labels: component/composition

#7489 release: v2.3.0
  .changesets/docs_baby_fellow_hard_historian.md
  .changesets/docs_ounce_caller_squash_motor.md
  .changesets/feat_andrew_deserializenonjson.md
  .changesets/feat_bnjjj_changeset_7070.md
  .changesets/feat_enhance_emitted_errors.md
  .changesets/feat_log_whether_enforcement_was_skipped.md
  .changesets/feat_zelda_add_response_body_selector.md
  .changesets/fix_am_bug_duplicatedropogateheader.md
  .changesets/fix_am_bug_variablenestedinputargument.md
  .changesets/fix_caroline_client_header.md
  .changesets/fix_caroline_demote_log_line.md
  .changesets/fix_caroline_telemetry_http_route.md
  .changesets/fix_garypen_allow_disabled_health_check.md
  .changesets/maint_caroline_redis.md
  .circleci/config.yml
  CHANGELOG.md
  Cargo.lock
  RELEASE_CHECKLIST.md
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router/Cargo.toml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
  xtask/src/commands/release.rs
  xtask/src/commands/release/process.rs
Labels: release

#7600 Fill out most Merger constructor logic (minus prepare_supergraph)
  apollo-federation/src/link/authenticated_spec_definition.rs
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/link/cost_spec_definition.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/inaccessible_spec_definition.rs
  apollo-federation/src/link/join_spec_definition.rs
  apollo-federation/src/link/mod.rs
  apollo-federation/src/link/policy_spec_definition.rs
  apollo-federation/src/link/requires_scopes_spec_definition.rs
  apollo-federation/src/link/spec.rs
  apollo-federation/src/link/spec_definition.rs
  apollo-federation/src/link/tag_spec_definition.rs
  apollo-federation/src/merger/compose_directive_manager.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/merger/mod.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/mod.rs
  apollo-federation/src/schema/referencer.rs
  apollo-federation/src/subgraph/typestate.rs
Labels: component/composition

#7616 docs: update preview/minVersion components (backport #7612)
  docs/source/routing/cloud/subscriptions.mdx
  docs/source/routing/configuration.mdx
  docs/source/routing/graphos-features.mdx
  docs/source/routing/graphos-reporting.mdx
  docs/source/routing/observability/telemetry/trace-exporters/overview.mdx
  docs/source/routing/operations/defer.mdx
  docs/source/routing/operations/file-upload.mdx
  docs/source/routing/operations/subscriptions/index.mdx
  docs/source/routing/performance/caching/entity.mdx
  docs/source/routing/performance/caching/in-memory.mdx
  docs/source/routing/performance/query-planner-pools.mdx
  docs/source/routing/query-planning/native-query-planner.mdx
  docs/source/routing/security/authorization.mdx
  docs/source/routing/security/csrf.mdx
  docs/source/routing/security/demand-control.mdx
  docs/source/routing/security/persisted-queries.mdx
  docs/source/routing/security/subgraph-authentication.mdx
  docs/source/routing/uplink.mdx
Labels: conflicts

#7614 refactor merge_enum code to its own file
  apollo-federation/src/merger/merge_enum.rs
  apollo-federation/src/merger/merge_union.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/merger/mod.rs
Labels: component/composition

#7606 feat(subscription): add operation_name label to apollo.router.opened.subscriptions counter
  .changesets/fix_bnjjj_add_operation_name_subscription_metric.md
  apollo-router/src/metrics/mod.rs
  apollo-router/src/notification.rs
  apollo-router/src/plugins/subscription.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/services/supergraph/tests.rs
  apollo-router/tests/integration/mod.rs
  apollo-router/tests/integration/subscription_load_test.rs
  dev-docs/metrics.md
  docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
Labels: backport-1.x

#7656 feat(subscription): add operation_name label to apollo.router.opened.subscriptions counter (backport #7606)
  .changesets/fix_bnjjj_add_operation_name_subscription_metric.md
  apollo-router/src/metrics/mod.rs
  apollo-router/src/notification.rs
  apollo-router/src/plugins/subscription.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/src/services/supergraph/tests.rs
  apollo-router/tests/integration/mod.rs
  apollo-router/tests/integration/subscription_load_test.rs
  dev-docs/metrics.md
  docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
Labels: conflicts

#7662 docs: break up kubernetes article (backport #7497)
  docs/shared/helm-show-router-output.mdx
  docs/source/routing/self-hosted/containerization/kubernetes.mdx
  docs/source/routing/self-hosted/containerization/kubernetes/extensibility.mdx
  docs/source/routing/self-hosted/containerization/kubernetes/metrics.mdx
  docs/source/routing/self-hosted/containerization/kubernetes/other-considerations.mdx
  docs/source/routing/self-hosted/containerization/kubernetes/quickstart.mdx
  docs/source/routing/self-hosted/index.mdx
Labels: conflicts

#7683 fix(subscription): set a valid graphql response for websocket handshake response (backport #7680)
  .changesets/fix_bnjjj_fix_coprocessor_subscription.md
  apollo-router/src/plugins/coprocessor/test.rs
  apollo-router/src/services/subgraph_service.rs
Labels: conflicts

#7707 chore: Fix release process
  xtask/src/commands/release.rs
Labels: backport-1.x

#7713 chore: Fix rendering helm chart for release process
  xtask/src/commands/release.rs
Labels: backport-1.x

#7742 Create schema-differ function for LSP
  apollo-federation/src/lib.rs
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/subgraph/mod.rs
Labels: component/composition

#7563 adding `@fromContext` directive validation
  apollo-federation/src/error/mod.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/validators/context.rs
  apollo-federation/src/schema/validators/from_context.rs
Labels: component/composition

#7772 fix(composition): make compose directive argument nullable
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/schema/schema_upgrader.rs
  apollo-federation/src/subgraph/mod.rs
  apollo-federation/src/subgraph/spec.rs
Labels: component/composition

#7670 Port shallow type addition for composition merge step
  apollo-federation/src/error/mod.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/merger/error_reporter.rs
  apollo-federation/src/merger/merge_enum.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/schema/position.rs
  apollo-federation/src/subgraph/typestate.rs
Labels: component/composition

#7740 feat(federation/composition): port `ValidationState`, except `validateTransition()`
  apollo-federation/src/composition/satisfiability.rs
  apollo-federation/src/composition/satisfiability/validation_state.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/graph_path/transition.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
Labels: component/composition

#7729 fix(federation/composition): fixed context spec's argument type computation
  apollo-federation/src/link/context_spec_definition.rs
Labels: component/composition

#7700 feat(federation/composition): ported `simpleValidationConditionResolver`
  apollo-federation/src/composition/satisfiability.rs
  apollo-federation/src/composition/satisfiability/conditions_validation.rs
  apollo-federation/src/query_graph/condition_resolver.rs
  apollo-federation/src/query_graph/graph_path/operation.rs
  apollo-federation/src/query_graph/graph_path/transition.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/utils/logging.rs
Labels: component/composition
