Repository apollographql/router, pull requests merged in 2025-02, with the labels that each got.

#6713 (Demand Control) Properly short-circuit __typename scoring on response fields
  apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_query.graphql
  apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_response.json
  apollo-router/src/plugins/demand_control/cost_calculator/snapshots/apollo_router__plugins__demand_control__cost_calculator__static_cost__tests__federated_query_with_typenames@logs.snap
  apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
Labels: backport-1.x

#6717 test(federation-cli): enable log printing from apollo-federation-cli
  Cargo.lock
  apollo-federation/cli/Cargo.toml
  apollo-federation/cli/src/main.rs
Labels: backport-1.x

#6651 improve generate fragment compression
  apollo-federation/src/operation/mod.rs
  apollo-federation/src/operation/optimize.rs
  apollo-federation/src/operation/selection_map.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/fragment_autogeneration.rs
  apollo-federation/tests/query_plan/supergraphs/works_with_key_chains.graphql
  apollo-router-benchmarks/src/shared.rs
  apollo-router/src/axum_factory/snapshots/apollo_router__axum_factory__tests__defer_is_not_buffered.snap
  apollo-router/src/plugin/test/mock/canned.rs
  apollo-router/src/plugins/authorization/tests.rs
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap
  apollo-router/src/plugins/cache/tests.rs
  apollo-router/src/plugins/connectors/tests/mod.rs
  apollo-router/src/services/router/snapshots/apollo_router__services__router__tests__escaped_quotes_in_string_literal.snap
  apollo-router/src/services/supergraph/tests.rs
  apollo-router/tests/fixtures/type_conditions/artwork.json
  apollo-router/tests/fixtures/type_conditions/artwork_disabled.json
  apollo-router/tests/fixtures/type_conditions/artwork_query_fragments_enabled.json
  apollo-router/tests/fixtures/type_conditions/search.json
  apollo-router/tests/fixtures/type_conditions/search_list_of_list.json
  apollo-router/tests/fixtures/type_conditions/search_list_of_list_of_list.json
  apollo-router/tests/fixtures/type_conditions/search_query_fragments_enabled.json
  apollo-router/tests/samples/core/defer/plan.json
  apollo-router/tests/samples/enterprise/entity-cache/defer/plan.json
  apollo-router/tests/samples/enterprise/entity-cache/invalidation-entity-key/plan.json
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_disabled-2.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_disabled.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled-2.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_generate_query_fragments-2.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_generate_query_fragments.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list-2.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list_of_list-2.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_list_of_list_of_list.snap
  apollo-router/tests/snapshots/type_conditions___test_type_conditions_enabled_shouldnt_make_article_fetch-2.snap
  apollo-router/tests/tracing_common/mod.rs
Labels: backport-1.x

#6497 docs: router request lifecycle
  docs/shared/diagrams/router-request-lifecycle-overview.mdx
  docs/shared/router-lifecycle-services.mdx
  docs/source/reference/router/telemetry/instrumentation/events.mdx
  docs/source/reference/router/telemetry/instrumentation/spans.mdx
  docs/source/routing/customization/overview.mdx
  docs/source/routing/observability/telemetry.mdx
  docs/source/routing/request-lifecycle.mdx
  docs/source/routing/security/authorization.mdx
Labels: backport-1.x

#6690 (fix) Header propagation rule passthrough
  .changesets/fix_bryn_header_propagation_or.md
  apollo-router/src/plugins/headers/fixtures/propagate_passthrough.router.yaml
  apollo-router/src/plugins/headers/fixtures/propagate_passthrough_defaulted.router.yaml
  apollo-router/src/plugins/headers/mod.rs
  apollo-router/src/plugins/test.rs
  docs/source/routing/header-propagation.mdx
Labels: backport-1.x

#6647 release: v1.60.0
  .changesets/docs_eh_instrumentation_examples.md
  .changesets/exp_bnjjj_fix_retry_metric.md
  .changesets/feat_bryn_named_runtime_channel.md
  .changesets/fix_fix_invalid_error_path.md
  .changesets/fix_junior_granddad_salami_dye.md
  .changesets/fix_query_hash_speedup.md
  .changesets/fix_simon_rayonless_sysinfo.md
  .changesets/fix_tninesling_demand_control_perf.md
  .changesets/fix_tninesling_subscription_operation_init.md
  .changesets/maint_renee_migrate_metrics_values.md
  .changesets/maint_simon_unbridge.md
  apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_query.graphql
  apollo-router/src/plugins/demand_control/cost_calculator/fixtures/federated_ships_typename_response.json
  apollo-router/src/plugins/demand_control/cost_calculator/snapshots/apollo_router__plugins__demand_control__cost_calculator__static_cost__tests__federated_query_with_typenames@logs.snap
  apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
  licenses.html
Labels: release

#6563 docs: update observability/telemetry overview pages
  docs/source/reference/router/telemetry/instrumentation/conditions.mdx
  docs/source/reference/router/telemetry/instrumentation/events.mdx
  docs/source/reference/router/telemetry/instrumentation/instruments.mdx
  docs/source/reference/router/telemetry/instrumentation/selectors.mdx
  docs/source/reference/router/telemetry/instrumentation/spans.mdx
  docs/source/reference/router/telemetry/instrumentation/standard-attributes.mdx
  docs/source/reference/router/telemetry/instrumentation/standard-instruments.mdx
  docs/source/reference/router/telemetry/log-exporters/overview.mdx
  docs/source/reference/router/telemetry/log-exporters/stdout.mdx
  docs/source/reference/router/telemetry/metrics-exporters/datadog.mdx
  docs/source/reference/router/telemetry/metrics-exporters/dynatrace.mdx
  docs/source/reference/router/telemetry/metrics-exporters/new-relic.mdx
  docs/source/reference/router/telemetry/metrics-exporters/otlp.mdx
  docs/source/reference/router/telemetry/metrics-exporters/overview.mdx
  docs/source/reference/router/telemetry/metrics-exporters/prometheus.mdx
  docs/source/reference/router/telemetry/trace-exporters/datadog.mdx
  docs/source/reference/router/telemetry/trace-exporters/dynatrace.mdx
  docs/source/reference/router/telemetry/trace-exporters/jaeger.mdx
  docs/source/reference/router/telemetry/trace-exporters/new-relic.mdx
  docs/source/reference/router/telemetry/trace-exporters/otlp.mdx
  docs/source/reference/router/telemetry/trace-exporters/overview.mdx
  docs/source/reference/router/telemetry/trace-exporters/zipkin.mdx
  docs/source/routing/observability/debugging-client-requests.mdx
  docs/source/routing/observability/index.mdx
  docs/source/routing/observability/otel-traces-to-prometheus.mdx
  docs/source/routing/observability/otel.mdx
  docs/source/routing/observability/telemetry.mdx
Labels: backport-1.x

#6498 feat(federation): query plan correctness checker
  apollo-federation/Cargo.toml
  apollo-federation/cli/Cargo.toml
  apollo-federation/cli/src/main.rs
  apollo-federation/src/correctness/mod.rs
  apollo-federation/src/correctness/query_plan_analysis.rs
  apollo-federation/src/correctness/query_plan_analysis_test.rs
  apollo-federation/src/correctness/response_shape.rs
  apollo-federation/src/correctness/response_shape_compare.rs
  apollo-federation/src/correctness/response_shape_test.rs
  apollo-federation/src/correctness/subgraph_constraint.rs
  apollo-federation/src/lib.rs
  apollo-federation/src/query_plan/query_planner.rs
Labels: backport-1.x

#6765 expose number of evaluated query plan options
  apollo-federation/src/error/mod.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-router/src/query_planner/query_planner_service.rs
Labels: backport-1.x

#6796 docs: clarify router download steps
  docs/source/reference/router/self-hosted-install.mdx
Labels: backport-1.x

#6804 Allow setting of service port in helm chart
  .changesets/helm_targetport_configuration.md
  helm/chart/router/templates/service.yaml
  helm/chart/router/values.yaml
Labels: backport-1.x

#6800 Prevent deadlocks on metrics shutdown
  apollo-router/src/metrics/aggregation.rs
Labels: backport-1.x

#6667 ROVER-263 Enable remote proxy downloads (same as #6244)
  .changesets/feat_remote_proxy_downloads.md
  scripts/install.sh
Labels: backport-1.x

#6809 chore: Delegate setting "latest" to RELEASE_CHECKLIST.md, rather than CI.
  .circleci/config.yml
  RELEASE_CHECKLIST.md
Labels: backport-1.x

#6798 Add more observability around WS handshake failures
  apollo-router/src/services/subgraph_service.rs
Labels: backport-1.x

#6820 Add more observability around WS handshake failures (backport #6798)
  apollo-router/src/services/subgraph_service.rs
Labels: conflicts

#6555 fix(federation): fixed a bug losing `__typename` selection in query plan
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/path_tree.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/introspection_typename_handling.rs
Labels: backport-1.x

#6748 docs: free plan changes
  docs/source/reference/graphos-features.mdx
  docs/source/routing/about-router.mdx
  docs/source/routing/cloud/index.mdx
  docs/source/routing/customization/coprocessor.mdx
  docs/source/routing/observability/index.mdx
  docs/source/routing/observability/otel-traces-to-prometheus.mdx
  docs/source/routing/observability/telemetry/instrumentation/events.mdx
  docs/source/routing/observability/telemetry/instrumentation/instruments.mdx
  docs/source/routing/observability/telemetry/instrumentation/spans.mdx
  docs/source/routing/operations/subscriptions/index.mdx
  docs/source/routing/security/authorization.mdx
  docs/source/routing/security/jwt.mdx
  docs/source/routing/security/router-authentication.mdx
  docs/source/routing/self-hosted/index.mdx
  docs/source/routing/self-hosted/resource-management.mdx
Labels: backport-1.x

#6826 docs: remove request retry mention from traffic-shaping
  docs/source/routing/performance/traffic-shaping.mdx
Labels: backport-1.x

#6806 Prevent deadlocks on metrics shutdown (backport #6800)
  apollo-router/src/metrics/aggregation.rs
Labels: conflicts

#6837 docs: add note for prometheus separator behavior
  docs/source/routing/observability/telemetry/metrics-exporters/prometheus.mdx
Labels: backport-1.x

#6842 Docs update for otlp_tracing_sampler >= 1.61
  docs/source/reference/upgrade/from-router-v1.mdx
  docs/source/routing/graphos-reporting.mdx
Labels: backport-1.x

#6836 Upgrade to Rust 1.85
  .circleci/config.yml
  Cargo.lock
  DEVELOPMENT.md
  apollo-federation/src/link/database.rs
  apollo-federation/src/operation/simplify.rs
  apollo-federation/src/sources/connect/json_selection/methods/future.rs
  apollo-router/Cargo.toml
  apollo-router/README.md
  apollo-router/src/apollo_studio_interop/mod.rs
  apollo-router/src/apollo_studio_interop/tests.rs
  apollo-router/src/configuration/cors.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/tests.rs
  apollo-router/src/context/extensions/mod.rs
  apollo-router/src/graphql/response.rs
  apollo-router/src/json_ext.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugins/rhai/engine.rs
  apollo-router/src/plugins/rhai/mod.rs
  apollo-router/src/plugins/telemetry/config_new/conditions.rs
  apollo-router/src/plugins/telemetry/formatters/json.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
  apollo-router/src/plugins/test.rs
  apollo-router/src/services/external.rs
  apollo-router/src/services/fetch.rs
  apollo-router/src/services/router.rs
  apollo-router/src/services/subgraph.rs
  apollo-router/src/services/supergraph.rs
  apollo-router/tests/common.rs
  apollo-router/tests/integration/file_upload.rs
  apollo-router/tests/integration/telemetry/mod.rs
  dockerfiles/diy/dockerfiles/Dockerfile.repo
  docs/source/routing/customization/custom-binary.mdx
  rust-toolchain.toml
Labels: backport-1.x

#6830 release: v1.61.0
  .changesets/config_garypen_promote_otel.md
  .changesets/config_trevor_stabilize_local_manifests.md
  .changesets/feat_feat_qp_dry_un.md
  .changesets/feat_remote_proxy_downloads.md
  .changesets/fix_bnjjj_fix_6441.md
  .changesets/fix_bryn_header_propagation_or.md
  .changesets/fix_lost_typename_attachment.md
  .changesets/maint_tninesling_skip_disabled_dc_plugin.md
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  docs/source/routing/about-v1.mdx
  docs/source/routing/graphos-reporting.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release
