Repository apollographql/router, pull requests merged in 2025-03, with the labels that each got.

#6876 docs: rhai api ref
  docs/source/routing/customization/rhai.mdx
Labels: backport-1.x

#6840 Ensure `build_query_plan()` cancels when the request cancels
  .changesets/fix_stance_intercom_body_director.md
  apollo-federation/src/error/mod.rs
  apollo-federation/src/operation/mod.rs
  apollo-federation/src/operation/tests/mod.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/path_tree.rs
  apollo-federation/src/query_plan/fetch_dependency_graph.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs
  apollo-router/src/compute_job.rs
  apollo-router/src/introspection.rs
  apollo-router/src/query_planner/query_planner_service.rs
  apollo-router/src/services/layers/query_analysis.rs
Labels: backport-1.x

#6931 Use explicit default on omitted telemetry endpoints (backport #6816)
  .changesets/fix_fix_oltp_enpoint_config.md
  apollo-router/src/plugins/telemetry/config.rs
  apollo-router/src/plugins/telemetry/endpoint.rs
  apollo-router/src/plugins/telemetry/otlp.rs
  apollo-router/src/plugins/telemetry/tracing/datadog/mod.rs
  apollo-router/src/plugins/telemetry/tracing/jaeger.rs
  apollo-router/src/plugins/telemetry/tracing/zipkin.rs
Labels: conflicts

#6947 fix(Cargo.lock): fixed a compliance error due to RUSTSEC-2025-0009 (backport #6946)
  Cargo.lock
Labels: conflicts

#6938 Update team names in CODEOWNERS (backport #6936)
  .github/CODEOWNERS
Labels: conflicts

#6939 Update team names in CODEOWNERS (backport #6936)
  .github/CODEOWNERS
Labels: conflicts

#6799 Entity caching: sort entity keys before hashing the key
  Cargo.lock
  Cargo.toml
  apollo-router/src/plugins/cache/entity.rs
  apollo-router/src/plugins/cache/invalidation.rs
Labels: backport-1.x

#6948 Entity caching: sort entity keys before hashing the key (backport #6799)
  Cargo.lock
  Cargo.toml
  apollo-router/src/plugins/cache/entity.rs
  apollo-router/src/plugins/cache/invalidation.rs
Labels: conflicts

#6962 Add exemption for RUSTSEC-2024-0437 and prevent adding new vulnerable dependencies
  deny.toml
Labels: backport-1.x

#6963 Add exemption for RUSTSEC-2024-0437 and prevent adding new vulnerable dependencies (backport #6962)
  deny.toml
Labels: conflicts

#6888 fix(entity_caching): do not include other fields from representation variable than the entity keys
  .changesets/fix_bnjjj_fix_entity_caching_entity_key.md
  Cargo.toml
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugins/cache/entity.rs
  apollo-router/src/plugins/cache/invalidation.rs
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-2.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-4.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-6.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap
  apollo-router/src/plugins/cache/tests.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/selection.rs
  apollo-router/tests/integration/redis.rs
Labels: backport-1.x

#6965 fix(entity_caching): do not include other fields from representation variable than the entity keys (backport #6888)
  .changesets/fix_bnjjj_fix_entity_caching_entity_key.md
  Cargo.lock
  Cargo.toml
  apollo-router/src/plugin/test/mock/subgraph.rs
  apollo-router/src/plugins/cache/entity.rs
  apollo-router/src/plugins/cache/invalidation.rs
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-2.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-4.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires-6.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__insert_with_requires.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_data.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-3.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-5.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private.snap
  apollo-router/src/plugins/cache/tests.rs
  apollo-router/src/query_planner/mod.rs
  apollo-router/src/query_planner/selection.rs
  apollo-router/tests/integration/redis.rs
Labels: conflicts

#6847 Upgrade to Rust 1.85 (backport #6836)
  .circleci/config.yml
  Cargo.lock
  DEVELOPMENT.md
  apollo-federation/src/link/database.rs
  apollo-federation/src/operation/simplify.rs
  apollo-router/Cargo.toml
  apollo-router/README.md
  apollo-router/src/apollo_studio_interop/mod.rs
  apollo-router/src/apollo_studio_interop/tests.rs
  apollo-router/src/configuration/cors.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/tests.rs
  apollo-router/src/context/extensions/mod.rs
  apollo-router/src/graphql/response.rs
  apollo-router/src/json_ext.rs
  apollo-router/src/plugins/rhai/engine.rs
  apollo-router/src/plugins/rhai/mod.rs
  apollo-router/src/plugins/telemetry/config_new/conditions.rs
  apollo-router/src/plugins/telemetry/formatters/json.rs
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/src/plugins/telemetry/tracing/apollo_telemetry.rs
  apollo-router/src/plugins/test.rs
  apollo-router/src/services/external.rs
  apollo-router/src/services/router.rs
  apollo-router/src/services/subgraph.rs
  apollo-router/src/services/supergraph.rs
  apollo-router/tests/common.rs
  apollo-router/tests/integration/file_upload.rs
  apollo-router/tests/integration/telemetry/mod.rs
  dockerfiles/diy/dockerfiles/Dockerfile.repo
  docs/source/routing/customization/custom-binary.mdx
  rust-toolchain.toml
Labels: conflicts

#7010 docs: remove out-of-band reporting (not applicable to router)
  docs/source/routing/observability/error-reporting.mdx
Labels: backport-1.x

#7013 doc: Add MinVersions for PQ configs
  docs/source/routing/security/persisted-queries.mdx
Labels: backport-1.x

#7005 Add configuration option to limit maximum batch size
  .changesets/feat_limit_client_batch_size.md
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/configuration/tests.rs
  apollo-router/src/services/query_batching/testdata/batch_exceeds_maximum_size_response.json
  apollo-router/src/services/router/service.rs
  apollo-router/src/services/router/tests.rs
  docs/source/routing/performance/query-batching.mdx
Labels: backport-1.x

#7044 Add configuration option to limit maximum batch size (backport #7005)
  .changesets/feat_limit_client_batch_size.md
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/configuration/tests.rs
  apollo-router/src/services/query_batching/testdata/batch_exceeds_maximum_size_response.json
  apollo-router/src/services/router/service.rs
  apollo-router/src/services/router/tests.rs
  docs/source/routing/performance/query-batching.mdx
Labels: conflicts

#7064 docs: update schema size limit
  docs/source/routing/uplink.mdx
Labels: backport-1.x

#7081 docs: update resource estimator copy
  docs/source/routing/self-hosted/resource-estimator.mdx
Labels: backport-1.x

#7092 stop logging JWKS (backport #7079)
  apollo-router/src/plugins/authentication/mod.rs
Labels: conflicts

#7097 docs: move router reference
  docs/source/routing/configuration.mdx
  docs/source/routing/configure-your-router.mdx
  docs/source/routing/customization/rhai-reference.mdx
  docs/source/routing/errors.mdx
  docs/source/routing/federation-version-support.mdx
  docs/source/routing/migration/from-gateway.mdx
  docs/source/routing/self-hosted/install.mdx
  docs/source/routing/upgrade/from-router-v0.mdx
  docs/source/routing/upgrade/from-router-v1.mdx
Labels: backport-1.x

#7098 docs: move router reference (backport #7097)
  docs/source/routing/configuration.mdx
  docs/source/routing/configure-your-router.mdx
  docs/source/routing/customization/rhai-reference.mdx
  docs/source/routing/errors.mdx
  docs/source/routing/federation-version-support.mdx
  docs/source/routing/migration/from-gateway.mdx
  docs/source/routing/self-hosted/install.mdx
  docs/source/routing/upgrade/from-router-v0.mdx
Labels: conflicts

#7099 docs: move graphos features page
  docs/source/routing/graphos-features.mdx
Labels: backport-1.x

#7091 Rename metric attribute `state` to `http.connection.state` (backport #7088)
  .changesets/feat_bryn_connection_metrics_2_0.md
  apollo-router/src/plugins/telemetry/config_new/instruments.rs
  docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
Labels: conflicts

#7106 Add changelog for `state`->`http.connection.state` rename
  .changesets/bug_bryn_connection_metrics_rename.md
Labels: backport-1.x

#7104 docs: move context callout
  docs/source/routing/customization/native-plugins.mdx
  docs/source/routing/graphos-reporting.mdx
Labels: backport-1.x

#7057 release: v1.61.1
  .changesets/feat_bryn_connection_metrics.md
  .changesets/feat_limit_client_batch_size.md
  .changesets/feat_pipeline_metrics.md
  .changesets/fix_bnjjj_fix_entity_caching_entity_key.md
  .changesets/fix_fix_oltp_enpoint_config.md
  .config/mise/config.toml
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7072 docs: add missing slash in the config path
  docs/source/routing/self-hosted/containerization/index.mdx
Labels: documentation, backport-1.x

#7127 Improve error message for invalid JWT Header values (backport #7121)
  .changesets/fix_improve_jwt_errors.md
  apollo-router/src/plugins/authentication/mod.rs
  apollo-router/src/plugins/authentication/tests.rs
Labels: conflicts
