Repository apollographql/router, pull requests merged in 2025-07, with the labels that each got.

#7773 release: v2.4.0
  .changesets/docs_jr_add_all_in_one_container_docs.md
  .changesets/docs_lambertjosh_readd_graph_docs.md
  .changesets/docs_lambertjosh_update_docker_docs_runtime.md
  .changesets/docs_lrlna_schema_load_duration.md
  .changesets/feat_caroline_consistent_on_error.md
  .changesets/feat_caroline_low_priority_warmup.md
  .changesets/feat_glasser_pq_error_include_extensions.md
  .changesets/feat_zelda_add_jwt_audience_validation.md
  .changesets/feat_zelda_feature_cooperative_cancellation.md
  .changesets/fix_bnjjj_add_operation_name_subscription_metric.md
  .changesets/fix_bnjjj_fix_coprocessor_subscription.md
  .changesets/fix_bnjjj_fix_telemetry_prom_resource.md
  .changesets/fix_caroline_coprocessor_on_graphql_error.md
  .changesets/fix_garypen_fix_otlp_http_metrics.md
  .changesets/fix_garypen_http_ext_clone_works_properly.md
  .changesets/fix_invalid_variable_error_message.md
  .changesets/fix_mantel_headband_iced_move.md
  .changesets/fix_qp_forbid_unknown_links.md
  .changesets/fix_query_plan_defer_invalid_root_type.md
  .changesets/maint_extended_errors_telemetry.md
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router/Cargo.toml
  docs/shared/k8s-manual-config.mdx
  docs/source/routing/errors.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7790 Port merge utility for merging directive applications
  apollo-federation/src/merger/error_reporter.rs
  apollo-federation/src/merger/merge_enum.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/schema/position.rs
  apollo-federation/src/schema/referencer.rs
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7792 feat(federation/composition): Port `validate_transition()`
  apollo-federation/src/composition/satisfiability/satisfiability_error.rs
  apollo-federation/src/composition/satisfiability/validation_state.rs
  apollo-federation/src/error/mod.rs
  apollo-federation/src/query_graph/build_query_graph.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/graph_path/operation.rs
  apollo-federation/src/query_graph/graph_path/transition.rs
  apollo-federation/src/query_graph/mod.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/utils/human_readable.rs
Labels: component/composition

#7807 fix(federation/composition): fixed `validate_federation_imports` to use the actual federation spec
  apollo-federation/src/link/authenticated_spec_definition.rs
  apollo-federation/src/link/database.rs
  apollo-federation/src/link/policy_spec_definition.rs
  apollo-federation/src/link/requires_scopes_spec_definition.rs
  apollo-federation/src/merger/merge_enum.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/subgraph/mod.rs
  apollo-federation/src/subgraph/spec.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/tests/dhat_profiling/supergraph.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7840 fix: @context locations should match JS definition
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/subgraph/mod.rs
Labels: component/composition

#7118 docs: move context callout (backport #7104)
  docs/source/routing/customization/native-plugins.mdx
  docs/source/routing/graphos-reporting.mdx
Labels: conflicts

#7881 Fix the subscription duplication problem when the client terminates the original subscription. (backport #7879)
  .changesets/fix_bnjjj_rh_924.md
  apollo-router/src/services/subgraph_service.rs
  apollo-router/tests/integration/subscriptions/mod.rs
  apollo-router/tests/integration/subscriptions/ws_passthrough.rs
Labels: conflicts

#7875 Support looking up a composition spec by a directive link and name
  apollo-federation/src/connectors/spec/mod.rs
  apollo-federation/src/link/authenticated_spec_definition.rs
  apollo-federation/src/link/cache_tag_spec_definition.rs
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/link/cost_spec_definition.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/inaccessible_spec_definition.rs
  apollo-federation/src/link/join_spec_definition.rs
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/src/link/policy_spec_definition.rs
  apollo-federation/src/link/requires_scopes_spec_definition.rs
  apollo-federation/src/link/spec_definition.rs
  apollo-federation/src/link/tag_spec_definition.rs
  apollo-federation/src/schema/mod.rs
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7916 refactor(federation): eliminated panics from `ArgumentComposition` implementations
  apollo-federation/cli/src/main.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/schema/argument_composition_strategies.rs
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7906 Implement logic for collecting and merging in imported specs
  apollo-federation/src/error/mod.rs
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/src/link/mod.rs
  apollo-federation/src/merger/merge_enum.rs
  apollo-federation/src/merger/merge_links.rs
  apollo-federation/src/merger/merger.rs
  apollo-federation/src/merger/mod.rs
Labels: component/composition

#7838 Added an error code for CompositionError::SubgraphError
  apollo-federation/src/error/mod.rs
Labels: component/composition

#7942 Add warning about dependencies to API shared with fedutils-build-plugins
  apollo-federation/src/subgraph/mod.rs
Labels: component/composition

#7902 release: v1.61.10
  .changesets/fix_bnjjj_rh_924.md
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.jaeger.yml
  docs/shared/k8s-manual-config.mdx
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7975 test(federation/composition): ported validation_errors.test.ts
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/tests/composition/mod.rs
  apollo-federation/tests/composition/validation_errors.rs
Labels: component/composition
