Repository apollographql/router, pull requests merged in 2025-04, with the labels that each got.

#7142 Tracing deadlock investigation
  .changesets/fix_caroline_deadlock.md
  apollo-router/src/plugins/telemetry/formatters/json.rs
  apollo-router/src/plugins/telemetry/otel/layer.rs
Labels: backport-1.x

#7143 [docs] Update in-memory cache warm up
  docs/source/routing/performance/caching/in-memory.mdx
Labels: backport-1.x

#7169 Tracing deadlock investigation (backport #7142)
  .changesets/fix_caroline_deadlock.md
  apollo-router/src/plugins/telemetry/formatters/json.rs
  apollo-router/src/plugins/telemetry/otel/layer.rs
Labels: conflicts

#7176 release: v1.61.2
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-federation/src/query_graph/build_query_graph.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/mod.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  apollo-router/src/configuration/metrics.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
  apollo-router/src/query_planner/query_planner_service.rs
  apollo-router/src/services/layers/query_analysis.rs
  apollo-router/src/spec/operation_limits.rs
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7177 release: v2.1.1
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-federation/src/query_graph/build_query_graph.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/mod.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
  apollo-federation/tests/dhat_profiling/query_plan.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides.rs
  apollo-federation/tests/query_plan/build_query_plan_tests/overrides/shareable.rs
  apollo-router-benchmarks/Cargo.toml
  apollo-router/Cargo.toml
  apollo-router/src/configuration/metrics.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__metrics__test__env_metrics.snap
  apollo-router/src/query_planner/query_planner_service.rs
  apollo-router/src/services/layers/query_analysis.rs
  apollo-router/src/spec/operation_limits.rs
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7195 Simplify `->` method tail handling, ensuring left associativity (backport #7144)
  apollo-federation/src/sources/connect/json_selection/apply_to.rs
  apollo-federation/src/sources/connect/json_selection/methods.rs
  apollo-federation/src/sources/connect/json_selection/methods/future.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/and.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/arithmetic.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/eq.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/get.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/has.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/keys.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/match_if.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/mod.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/not.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/or.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/snapshots/apollo_federation__sources__connect__json_selection__methods__future__get__tests__get_should_correct_call_methods_with_extra_spaces.snap
  apollo-federation/src/sources/connect/json_selection/methods/future/typeof.rs
  apollo-federation/src/sources/connect/json_selection/methods/future/values.rs
  apollo-federation/src/sources/connect/json_selection/methods/public.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/echo.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/entries.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/first.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/json_stringify.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/last.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/map.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/match.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/mod.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/size.rs
  apollo-federation/src/sources/connect/json_selection/methods/public/slice.rs
  apollo-federation/src/sources/connect/json_selection/methods/tests.rs
Labels: conflicts

#7205 Adjust compute job worker pool queue size
  apollo-router/src/compute_job.rs
Labels: backport-1.x

#7216 Add compute pool metrics (backport #7184)
  .changesets/fix_caroline_compute_pool_metrics.md
  apollo-router/src/compute_job/metrics.rs
  apollo-router/src/compute_job/mod.rs
  apollo-router/src/introspection.rs
  apollo-router/src/query_planner/query_planner_service.rs
  apollo-router/src/services/layers/query_analysis.rs
  apollo-router/tests/integration/telemetry/metrics.rs
  docs/source/routing/observability/telemetry/instrumentation/standard-instruments.mdx
Labels: conflicts

#7236 Add spans for compute jobs
  .changesets/feat_bryn_compute_job_spans.md
  apollo-router/src/ageing_priority_queue.rs
  apollo-router/src/compute_job/metrics.rs
  apollo-router/src/compute_job/mod.rs
  apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap
  apollo-router/src/plugins/telemetry/consts.rs
  apollo-router/src/services/layers/query_analysis.rs
  apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__batch_send_header.snap
  apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__batch_trace_id.snap
  apollo-router/tests/snapshots/apollo_otel_traces__client_name-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__client_name.snap
  apollo-router/tests/snapshots/apollo_otel_traces__client_version-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__client_version.snap
  apollo-router/tests/snapshots/apollo_otel_traces__condition_else-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__condition_else.snap
  apollo-router/tests/snapshots/apollo_otel_traces__condition_if-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__condition_if.snap
  apollo-router/tests/snapshots/apollo_otel_traces__non_defer-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__non_defer.snap
  apollo-router/tests/snapshots/apollo_otel_traces__send_header-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__send_header.snap
  apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__send_variable_value.snap
  apollo-router/tests/snapshots/apollo_otel_traces__trace_id-2.snap
  apollo-router/tests/snapshots/apollo_otel_traces__trace_id.snap
Labels: backport-1.x

#7182 docs: update serverless request limits to include subscription limits
  docs/source/routing/cloud/serverless.mdx
Labels: documentation

#7266 Add more flexible subgraph mocks, take 2 (backport #7060)
  apollo-router/src/batching.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/plugin/mod.rs
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__no_cache_control-4.snap
  apollo-router/src/plugins/cache/snapshots/apollo_router__plugins__cache__tests__private-6.snap
  apollo-router/src/plugins/cache/tests.rs
  apollo-router/src/plugins/mock_subgraphs/execution/engine.rs
  apollo-router/src/plugins/mock_subgraphs/execution/input_coercion.rs
  apollo-router/src/plugins/mock_subgraphs/execution/mod.rs
  apollo-router/src/plugins/mock_subgraphs/execution/resolver.rs
  apollo-router/src/plugins/mock_subgraphs/execution/result_coercion.rs
  apollo-router/src/plugins/mock_subgraphs/execution/validation.rs
  apollo-router/src/plugins/mock_subgraphs/mod.rs
  apollo-router/src/plugins/mod.rs
  apollo-router/src/plugins/progressive_override/snapshots/apollo_router__plugins__progressive_override__tests__non_overridden_field_yields_expected_query_plan.snap
  apollo-router/src/plugins/progressive_override/snapshots/apollo_router__plugins__progressive_override__tests__overridden_field_yields_expected_query_plan.snap
  apollo-router/src/plugins/progressive_override/tests.rs
  apollo-router/src/router_factory.rs
  apollo-router/src/test_harness.rs
  dev-docs/mock_subgraphs_plugin.md
Labels: conflicts

#7258 Fix JWT metrics discrepancy
  .changesets/fix_simon_jwt_metrics.md
  apollo-router/src/plugins/authentication/mod.rs
Labels: backport-1.x

#7287 docs: add changeset for #7205
  .changesets/fix_renee_increase_compute_job_queue.md
Labels: backport-1.x

#7284 Fix helm template syntax for virtualservice `Hosts` list
  helm/chart/router/templates/virtualservice.yaml
Labels: backport-1.x

#7291 Fix JWT metrics discrepancy (backport #7258)
  .changesets/fix_simon_jwt_metrics.md
  apollo-router/src/plugins/authentication/mod.rs
Labels: conflicts

#7309 Use snake case for metric values (backport #7308)
  .changesets/fix_caroline_compute_pool_metrics.md
  apollo-router/src/compute_job/metrics.rs
  apollo-router/src/compute_job/mod.rs
  apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap
  apollo-router/tests/integration/telemetry/metrics.rs
Labels: conflicts

#7315 coprocessor: fix parsing of graphql responses with null as `data` (backport #7141)
  .changesets/fix_fix_coprocessor_data_null.md
  apollo-router/src/graphql/mod.rs
  apollo-router/src/graphql/request.rs
  apollo-router/src/graphql/response.rs
  apollo-router/src/graphql/visitor.rs
  apollo-router/src/plugins/coprocessor/execution.rs
  apollo-router/src/plugins/coprocessor/mod.rs
  apollo-router/src/plugins/coprocessor/supergraph.rs
  apollo-router/src/plugins/coprocessor/test.rs
  apollo-router/src/plugins/demand_control/cost_calculator/static_cost.rs
  apollo-router/src/services/subgraph_service.rs
  apollo-router/tests/integration/coprocessor.rs
Labels: conflicts

#7334 docs: otlp metrics exporters
  docs/source/routing/observability/telemetry/metrics-exporters/datadog.mdx
  docs/source/routing/observability/telemetry/metrics-exporters/dynatrace.mdx
  docs/source/routing/observability/telemetry/metrics-exporters/new-relic.mdx
  docs/source/routing/observability/telemetry/metrics-exporters/otlp.mdx
Labels: backport-1.x

#7301 release: v1.61.5
  .changesets/feat_bryn_compute_job_spans.md
  .changesets/feat_bryn_connection_metrics_2_0.md
  .changesets/fix_bryn_connection_shutdown_timeout_1_x.md
  .changesets/fix_bryn_poll_pending_compute_jobs.md
  .changesets/fix_caroline_compute_pool_metrics.md
  .changesets/fix_caroline_deadlock.md
  .changesets/fix_duckki_entity_cache_matching_key.md
  .changesets/fix_improve_jwt_errors.md
  .changesets/fix_renee_bail_invalid_query_plans.md
  .changesets/fix_renee_increase_compute_job_queue.md
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  apollo-router/src/compute_job/metrics.rs
  apollo-router/src/compute_job/mod.rs
  apollo-router/src/compute_job/snapshots/apollo_router__compute_job__tests__observability@logs.snap
  apollo-router/tests/integration/telemetry/metrics.rs
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
Labels: release

#7306 Fix metric `apollo.router.operations.batching.size`
  .changesets/fix_bnjjj_rh_845.md
  apollo-router/src/graphql/request.rs
  apollo-router/src/services/router/tests.rs
Labels: backport-1.x

#7362 Fix metric `apollo.router.operations.batching.size` (backport #7306)
  .changesets/fix_bnjjj_rh_845.md
  apollo-router/src/graphql/request.rs
  apollo-router/src/services/router/tests.rs
Labels: conflicts

#7353 Add configurable server header read timeout (backport #7262)
  .changesets/config_header_read_timeout.md
  apollo-router/src/axum_factory/axum_http_server_factory.rs
  apollo-router/src/configuration/mod.rs
  apollo-router/src/configuration/server.rs
  apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap
  apollo-router/src/configuration/tests.rs
  docs/source/routing/configuration.mdx
Labels: conflicts

#7330 release: v2.2.0
  .changesets/bug_bryn_connection_metrics_rename.md
  .changesets/config_apollo_otlp_realtime_studio_metrics.md
  .changesets/config_header_read_timeout.md
  .changesets/config_subgraph_include_errors allow_and_deny_list.md
  .changesets/docs_pillow_snack_joke_corduroy.md
  .changesets/docs_timbotnik_errors_preview_docs.md
  .changesets/docs_timbotnik_pulsr_1484_graphos_error_docs.md
  .changesets/docs_vulture_companion_residence_yarn.md
  .changesets/feat_6172_jwtmultipleissuers.md
  .changesets/feat_bnjjj_config_auto_migration.md
  .changesets/feat_bryn_compute_job_spans.md
  .changesets/feat_connectors_uri_expression_locations.md
  .changesets/feat_coprocessorhttprequestspan.md
  .changesets/feat_enhanced_client_awareness.md
  .changesets/feat_feature_connectorsyamlheaders.md
  .changesets/feat_persisted_query_reporting.md
  .changesets/fix_bnjjj_fix_log_with_subs_jwt.md
  .changesets/fix_bryn_connection_shutdown_timeout_1_x.md
  .changesets/fix_caroline_compute_pool_metrics.md
  .changesets/fix_caroline_deadlock.md
  .changesets/fix_connectors_percent_encoding.md
  .changesets/fix_connectors_trailing_slashes.md
  .changesets/fix_curly_think_heap_glue.md
  .changesets/fix_duckki_entity_cache_matching_key.md
  .changesets/fix_error_apollo_operation_id_fix.md
  .changesets/fix_events_conditions.md
  .changesets/fix_fix_coprocessor_data_null.md
  .changesets/fix_fix_docker_image_fix_for_cloudrun.md
  .changesets/fix_heap_tail_paper_bunk.md
  .changesets/fix_improve_jwt_errors.md
  .changesets/fix_meryl_pulsr_1429.md
  .changesets/fix_renee_bail_invalid_query_plans.md
  .changesets/fix_renee_increase_compute_job_queue.md
  .changesets/fix_router-external-extensibility-deprecation.md
  .changesets/fix_rreg_int_err_codes_fix.md
  .changesets/fix_simon_jwt_metrics.md
  .changesets/fix_simon_unwarn_resource_attr.md
  .changesets/helm_targetport_configuration.md
  CHANGELOG.md
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  licenses.html
  scripts/install.sh
Labels: release

#7367 docs: trace exporters
  docs/source/routing/observability/telemetry/trace-exporters/datadog.mdx
  docs/source/routing/observability/telemetry/trace-exporters/dynatrace.mdx
  docs/source/routing/observability/telemetry/trace-exporters/jaeger.mdx
  docs/source/routing/observability/telemetry/trace-exporters/new-relic.mdx
  docs/source/routing/observability/telemetry/trace-exporters/overview.mdx
Labels: backport-1.x

#7350 deps: update apollo-compiler (backport #7338)
  .changesets/maint_renee_apollo_compiler_1_28.md
  Cargo.lock
  Cargo.toml
  apollo-federation/tests/api_schema.rs
Labels: conflicts

#7358 Fix typo in distributed caching docs
  docs/source/routing/performance/caching/distributed.mdx
Labels: backport-1.x
