Repository apollographql/router, pull requests merged in 2025-05, with the labels that each got.

#7373 docs: typo on PQ docs
  docs/source/routing/security/persisted-queries.mdx
Labels: backport-1.x

#7400 Fix broken link to in-memory caching docs page
  docs/source/routing/performance/caching/distributed.mdx
Labels: backport-1.x

#7369 fix: propagate client name and version modifications through telemetry
  .changesets/fix_caroline_client_header.md
  apollo-router/src/plugins/telemetry/mod.rs
  apollo-router/tests/integration/telemetry/datadog.rs
  apollo-router/tests/integration/telemetry/fixtures/otlp_override_client_name.router.yaml
  apollo-router/tests/integration/telemetry/fixtures/override_client_name.rhai
  apollo-router/tests/integration/telemetry/mod.rs
  apollo-router/tests/integration/telemetry/otlp.rs
Labels: backport-1.x

#7421 Un-box statically-defined supergraph specifications
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/link/cost_spec_definition.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/inaccessible_spec_definition.rs
  apollo-federation/src/link/join_spec_definition.rs
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/src/link/spec_definition.rs
  apollo-federation/src/merge.rs
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7420 FederationBlueprint callback implementations
  Cargo.lock
  apollo-federation/Cargo.toml
  apollo-federation/cli/src/main.rs
  apollo-federation/src/error/mod.rs
  apollo-federation/src/error/suggestion.rs
  apollo-federation/src/query_plan/query_planner.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/schema_upgrader.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7424 Docs: Update Header from Acronym to Full Terminology
  docs/source/routing/cloud/dedicated.mdx
Labels: backport-1.x

#7399 Update FieldSet validations to match expectations from subgraph tests
  apollo-federation/src/error/mod.rs
  apollo-federation/src/schema/mod.rs
  apollo-federation/src/schema/position.rs
  apollo-federation/src/schema/subgraph_metadata.rs
  apollo-federation/src/schema/validators/key.rs
  apollo-federation/src/schema/validators/mod.rs
  apollo-federation/src/schema/validators/provides.rs
  apollo-federation/src/schema/validators/requires.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7409 Manage all CI versions through mise and use binstall (backport #7393)
  .circleci/config.yml
  .config/mise/config.ci-mac.toml
  .config/mise/config.ci.toml
  .config/mise/config.toml
  .config/mise/config.windows.toml
Labels: conflicts

#7466 chore: tweak mise usage on CI
  .circleci/config.yml
Labels: backport-1.x

#7454 federation: implement composition stubs
  apollo-federation/cli/src/main.rs
  apollo-federation/src/composition/mod.rs
  apollo-federation/src/composition/satisfiability.rs
  apollo-federation/src/lib.rs
  apollo-federation/src/schema/schema_upgrader.rs
  apollo-federation/src/subgraph/mod.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/src/supergraph/mod.rs
Labels: component/composition

#7455 Hoist root type normalization up to expanded subgraph stage
  apollo-federation/cli/src/main.rs
  apollo-federation/src/composition/mod.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/subgraph/mod.rs
  apollo-federation/src/subgraph/typestate.rs
Labels: component/composition

#7471 add space after comma
  docs/source/routing/graphos-features.mdx
Labels: backport-1.x

#7451 Implement post-merge validations
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/validators/interface_object.rs
  apollo-federation/src/schema/validators/merged.rs
  apollo-federation/src/schema/validators/mod.rs
  apollo-federation/src/utils/human_readable.rs
Labels: component/composition

#7456 fix(federation/composition): updated spec link bootstrapping to match JS version
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/mod.rs
  apollo-federation/src/schema/subgraph_metadata.rs
  apollo-federation/src/subgraph/mod.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7408 Support `span_attributes` testing in datadog and OTLP exporters (backport #7369)
  apollo-router/tests/integration/telemetry/datadog.rs
  apollo-router/tests/integration/telemetry/otlp.rs
Labels: conflicts

#7492 Update coprocessor.mdx
  docs/source/routing/customization/coprocessor.mdx
Labels: backport-1.x, support

#7482 Properly categorize and surface FieldSet validation messages during directive validation
  apollo-federation/src/schema/field_set.rs
  apollo-federation/src/schema/subgraph_metadata.rs
  apollo-federation/src/schema/validators/key.rs
  apollo-federation/src/schema/validators/mod.rs
  apollo-federation/src/schema/validators/provides.rs
  apollo-federation/src/schema/validators/requires.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7501 chore(federation/composition): removed a comment link mentioning FED-172
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7502 chore(federation/composition): fixed a few `custom_error_message_for_misnamed_directives` tests
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7504 Port specs for inaccessible and tag
  Cargo.lock
  Cargo.toml
  apollo-federation/Cargo.toml
  apollo-federation/src/link/context_spec_definition.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/inaccessible_spec_definition.rs
  apollo-federation/src/link/link_spec_definition.rs
  apollo-federation/src/link/mod.rs
  apollo-federation/src/link/spec.rs
  apollo-federation/src/link/tag_spec_definition.rs
  apollo-federation/src/schema/position.rs
  apollo-federation/src/schema/schema_upgrader.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
  apollo-router/Cargo.toml
Labels: component/composition

#7514 chore: update composition stubs
  apollo-federation/src/composition/mod.rs
  apollo-federation/src/supergraph/mod.rs
Labels: component/composition

#7516 [docs] Update client-id-enforcement.mdx
  docs/source/routing/observability/client-id-enforcement.mdx
Labels: backport-1.x

#7524 feat(federation/composition): Add `TransitionGraphPath` and switch to `UnadvanceableClosures`
  apollo-federation/src/query_graph/graph_path.rs
Labels: component/query-planning, component/composition

#7523 Update Router request termination docs
  docs/source/routing/customization/rhai/reference.mdx
Labels: backport-1.x

#7527 Port join spec
  apollo-federation/src/link/join_spec_definition.rs
  apollo-federation/src/schema/type_and_directive_specification.rs
Labels: component/composition

#7530 docs: fix spelling of `probabilistic_sampling` option
  docs/source/routing/observability/telemetry/trace-exporters/datadog.mdx
Labels: backport-1.x

#7532 Port auth specs
  apollo-federation/src/link/authenticated_spec_definition.rs
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/link/mod.rs
  apollo-federation/src/link/policy_spec_definition.rs
  apollo-federation/src/link/requires_scopes_spec_definition.rs
  apollo-federation/src/link/spec.rs
  apollo-federation/src/schema/blueprint.rs
Labels: component/composition

#7547 chore(federation/composition): Split trigger-specific code from `graph_path.rs`
  apollo-federation/src/operation/mod.rs
  apollo-federation/src/operation/tests/mod.rs
  apollo-federation/src/query_graph/condition_resolver.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/graph_path/operation.rs
  apollo-federation/src/query_graph/graph_path/transition.rs
  apollo-federation/src/query_graph/mod.rs
  apollo-federation/src/query_graph/path_tree.rs
  apollo-federation/src/query_plan/conditions.rs
  apollo-federation/src/query_plan/fetch_dependency_graph.rs
  apollo-federation/src/query_plan/fetch_dependency_graph_processor.rs
  apollo-federation/src/query_plan/query_planning_traversal.rs
  apollo-federation/src/query_plan/query_planning_traversal/non_local_selections_estimation.rs
  apollo-federation/src/utils/logging.rs
Labels: component/composition

#6882 docs: tweak language around GraphOS + OTLP trace reporting
  docs/source/routing/graphos-reporting.mdx
Labels: backport-1.x

#7549 Port tag and shareable validations
  apollo-federation/src/schema/blueprint.rs
  apollo-federation/src/schema/validators/mod.rs
  apollo-federation/src/schema/validators/shareable.rs
  apollo-federation/tests/subgraph/subgraph_validation_tests.rs
Labels: component/composition

#7558 release: v1.61.7
  .changesets/feat_log_whether_enforcement_was_skipped.md
  .circleci/config.yml
  CHANGELOG.md
  Cargo.lock
  RELEASE_CHECKLIST.md
  apollo-federation/Cargo.toml
  apollo-router-benchmarks/Cargo.toml
  apollo-router-scaffold/Cargo.toml
  apollo-router-scaffold/templates/base/Cargo.template.toml
  apollo-router-scaffold/templates/base/xtask/Cargo.template.toml
  apollo-router/Cargo.toml
  dockerfiles/tracing/docker-compose.datadog.yml
  dockerfiles/tracing/docker-compose.jaeger.yml
  dockerfiles/tracing/docker-compose.zipkin.yml
  helm/chart/router/Chart.yaml
  helm/chart/router/README.md
  scripts/install.sh
Labels: release

#7574 federation: add missing subgraph and supergraph typestate transitions
  apollo-federation/src/schema/mod.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/src/supergraph/mod.rs
Labels: component/composition

#7572 adding some scaffolding for merge code as well as some error reporting code
  apollo-federation/src/merge/error_reporter.rs
  apollo-federation/src/merge/hints.rs
  apollo-federation/src/merge/merger.rs
  apollo-federation/src/subgraph/typestate.rs
  apollo-federation/src/supergraph/mod.rs
Labels: component/composition

#7546 feat(federation/composition): port `advancePathWithDirectTransition()`
  apollo-federation/src/link/federation_spec_definition.rs
  apollo-federation/src/query_graph/condition_resolver.rs
  apollo-federation/src/query_graph/graph_path.rs
  apollo-federation/src/query_graph/graph_path/transition.rs
  apollo-federation/src/query_graph/mod.rs
Labels: component/composition
